/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppAccountantIndexRouteImport } from './routes/_app/accountant/index'
import { Route as AppAccountantSplatRouteImport } from './routes/_app/accountant/$'
import { Route as AppAccountantAppointmentsRouteImport } from './routes/_app/accountant/appointments'
import { Route as AppAccountantBillsRouteImport } from './routes/_app/accountant/bills'
import { Route as AppAccountantCalendarRouteImport } from './routes/_app/accountant/calendar'
import { Route as AppAccountantDashboardRouteImport } from './routes/_app/accountant/dashboard'
import { Route as AppAccountantDoctorsRouteImport } from './routes/_app/accountant/doctors'
import { Route as AppAccountantPatientsRouteImport } from './routes/_app/accountant/patients'
import { Route as AppAccountantReportsRouteImport } from './routes/_app/accountant/reports'
import { Route as AppAdminIndexRouteImport } from './routes/_app/admin/index'
import { Route as AppAdminSplatRouteImport } from './routes/_app/admin/$'
import { Route as AppAdminAppointmentsRouteImport } from './routes/_app/admin/appointments'
import { Route as AppAdminAuditLogsRouteImport } from './routes/_app/admin/audit-logs'
import { Route as AppAdminBillsRouteImport } from './routes/_app/admin/bills'
import { Route as AppAdminCalendarRouteImport } from './routes/_app/admin/calendar'
import { Route as AppAdminDashboardRouteImport } from './routes/_app/admin/dashboard'
import { Route as AppAdminDoctorsRouteImport } from './routes/_app/admin/doctors'
import { Route as AppAdminMedicalRecordsRouteImport } from './routes/_app/admin/medical-records'
import { Route as AppAdminPatientsRouteImport } from './routes/_app/admin/patients'
import { Route as AppAdminReportsRouteImport } from './routes/_app/admin/reports'
import { Route as AppAdminUsersRouteImport } from './routes/_app/admin/users'
import { Route as AppDoctorIndexRouteImport } from './routes/_app/doctor/index'
import { Route as AppDoctorSplatRouteImport } from './routes/_app/doctor/$'
import { Route as AppDoctorAppointmentsRouteImport } from './routes/_app/doctor/appointments'
import { Route as AppDoctorCalendarRouteImport } from './routes/_app/doctor/calendar'
import { Route as AppDoctorDashboardRouteImport } from './routes/_app/doctor/dashboard'
import { Route as AppDoctorDoctorProfileRouteImport } from './routes/_app/doctor/doctor-profile'
import { Route as AppDoctorMedicalRecordsRouteImport } from './routes/_app/doctor/medical-records'
import { Route as AppPatientIndexRouteImport } from './routes/_app/patient/index'
import { Route as AppPatientSplatRouteImport } from './routes/_app/patient/$'
import { Route as AppReceptionistIndexRouteImport } from './routes/_app/receptionist/index'
import { Route as AppReceptionistSplatRouteImport } from './routes/_app/receptionist/$'
import { Route as AppReceptionistAppointmentsRouteImport } from './routes/_app/receptionist/appointments'
import { Route as AppReceptionistBillsRouteImport } from './routes/_app/receptionist/bills'
import { Route as AppReceptionistCalendarRouteImport } from './routes/_app/receptionist/calendar'
import { Route as AppReceptionistDashboardRouteImport } from './routes/_app/receptionist/dashboard'
import { Route as AppReceptionistDoctorsRouteImport } from './routes/_app/receptionist/doctors'
import { Route as AppReceptionistPatientsRouteImport } from './routes/_app/receptionist/patients'
import { Route as AppSuperAdminIndexRouteImport } from './routes/_app/super-admin/index'
import { Route as AppSuperAdminSplatRouteImport } from './routes/_app/super-admin/$'
import { Route as AppSuperAdminAppointmentsRouteImport } from './routes/_app/super-admin/appointments'
import { Route as AppSuperAdminAuditLogsRouteImport } from './routes/_app/super-admin/audit-logs'
import { Route as AppSuperAdminBillsRouteImport } from './routes/_app/super-admin/bills'
import { Route as AppSuperAdminCalendarRouteImport } from './routes/_app/super-admin/calendar'
import { Route as AppSuperAdminDashboardRouteImport } from './routes/_app/super-admin/dashboard'
import { Route as AppSuperAdminDoctorsRouteImport } from './routes/_app/super-admin/doctors'
import { Route as AppSuperAdminMedicalRecordsRouteImport } from './routes/_app/super-admin/medical-records'
import { Route as AppSuperAdminPatientsRouteImport } from './routes/_app/super-admin/patients'
import { Route as AppSuperAdminReportsRouteImport } from './routes/_app/super-admin/reports'
import { Route as AppSuperAdminUsersRouteImport } from './routes/_app/super-admin/users'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountantIndexRoute = AppAccountantIndexRouteImport.update({
  id: '/accountant/',
  path: '/accountant/',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountantSplatRoute = AppAccountantSplatRouteImport.update({
  id: '/accountant/$',
  path: '/accountant/$',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountantAppointmentsRoute =
  AppAccountantAppointmentsRouteImport.update({
    id: '/accountant/appointments',
    path: '/accountant/appointments',
    getParentRoute: () => AppRoute,
  } as any)
const AppAccountantBillsRoute = AppAccountantBillsRouteImport.update({
  id: '/accountant/bills',
  path: '/accountant/bills',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountantCalendarRoute = AppAccountantCalendarRouteImport.update({
  id: '/accountant/calendar',
  path: '/accountant/calendar',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountantDashboardRoute = AppAccountantDashboardRouteImport.update({
  id: '/accountant/dashboard',
  path: '/accountant/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountantDoctorsRoute = AppAccountantDoctorsRouteImport.update({
  id: '/accountant/doctors',
  path: '/accountant/doctors',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountantPatientsRoute = AppAccountantPatientsRouteImport.update({
  id: '/accountant/patients',
  path: '/accountant/patients',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountantReportsRoute = AppAccountantReportsRouteImport.update({
  id: '/accountant/reports',
  path: '/accountant/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminIndexRoute = AppAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminSplatRoute = AppAdminSplatRouteImport.update({
  id: '/admin/$',
  path: '/admin/$',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminAppointmentsRoute = AppAdminAppointmentsRouteImport.update({
  id: '/admin/appointments',
  path: '/admin/appointments',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminAuditLogsRoute = AppAdminAuditLogsRouteImport.update({
  id: '/admin/audit-logs',
  path: '/admin/audit-logs',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminBillsRoute = AppAdminBillsRouteImport.update({
  id: '/admin/bills',
  path: '/admin/bills',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminCalendarRoute = AppAdminCalendarRouteImport.update({
  id: '/admin/calendar',
  path: '/admin/calendar',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminDashboardRoute = AppAdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminDoctorsRoute = AppAdminDoctorsRouteImport.update({
  id: '/admin/doctors',
  path: '/admin/doctors',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminMedicalRecordsRoute = AppAdminMedicalRecordsRouteImport.update({
  id: '/admin/medical-records',
  path: '/admin/medical-records',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminPatientsRoute = AppAdminPatientsRouteImport.update({
  id: '/admin/patients',
  path: '/admin/patients',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminReportsRoute = AppAdminReportsRouteImport.update({
  id: '/admin/reports',
  path: '/admin/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminUsersRoute = AppAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AppRoute,
} as any)
const AppDoctorIndexRoute = AppDoctorIndexRouteImport.update({
  id: '/doctor/',
  path: '/doctor/',
  getParentRoute: () => AppRoute,
} as any)
const AppDoctorSplatRoute = AppDoctorSplatRouteImport.update({
  id: '/doctor/$',
  path: '/doctor/$',
  getParentRoute: () => AppRoute,
} as any)
const AppDoctorAppointmentsRoute = AppDoctorAppointmentsRouteImport.update({
  id: '/doctor/appointments',
  path: '/doctor/appointments',
  getParentRoute: () => AppRoute,
} as any)
const AppDoctorCalendarRoute = AppDoctorCalendarRouteImport.update({
  id: '/doctor/calendar',
  path: '/doctor/calendar',
  getParentRoute: () => AppRoute,
} as any)
const AppDoctorDashboardRoute = AppDoctorDashboardRouteImport.update({
  id: '/doctor/dashboard',
  path: '/doctor/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppDoctorDoctorProfileRoute = AppDoctorDoctorProfileRouteImport.update({
  id: '/doctor/doctor-profile',
  path: '/doctor/doctor-profile',
  getParentRoute: () => AppRoute,
} as any)
const AppDoctorMedicalRecordsRoute = AppDoctorMedicalRecordsRouteImport.update({
  id: '/doctor/medical-records',
  path: '/doctor/medical-records',
  getParentRoute: () => AppRoute,
} as any)
const AppPatientIndexRoute = AppPatientIndexRouteImport.update({
  id: '/patient/',
  path: '/patient/',
  getParentRoute: () => AppRoute,
} as any)
const AppPatientSplatRoute = AppPatientSplatRouteImport.update({
  id: '/patient/$',
  path: '/patient/$',
  getParentRoute: () => AppRoute,
} as any)
const AppReceptionistIndexRoute = AppReceptionistIndexRouteImport.update({
  id: '/receptionist/',
  path: '/receptionist/',
  getParentRoute: () => AppRoute,
} as any)
const AppReceptionistSplatRoute = AppReceptionistSplatRouteImport.update({
  id: '/receptionist/$',
  path: '/receptionist/$',
  getParentRoute: () => AppRoute,
} as any)
const AppReceptionistAppointmentsRoute =
  AppReceptionistAppointmentsRouteImport.update({
    id: '/receptionist/appointments',
    path: '/receptionist/appointments',
    getParentRoute: () => AppRoute,
  } as any)
const AppReceptionistBillsRoute = AppReceptionistBillsRouteImport.update({
  id: '/receptionist/bills',
  path: '/receptionist/bills',
  getParentRoute: () => AppRoute,
} as any)
const AppReceptionistCalendarRoute = AppReceptionistCalendarRouteImport.update({
  id: '/receptionist/calendar',
  path: '/receptionist/calendar',
  getParentRoute: () => AppRoute,
} as any)
const AppReceptionistDashboardRoute =
  AppReceptionistDashboardRouteImport.update({
    id: '/receptionist/dashboard',
    path: '/receptionist/dashboard',
    getParentRoute: () => AppRoute,
  } as any)
const AppReceptionistDoctorsRoute = AppReceptionistDoctorsRouteImport.update({
  id: '/receptionist/doctors',
  path: '/receptionist/doctors',
  getParentRoute: () => AppRoute,
} as any)
const AppReceptionistPatientsRoute = AppReceptionistPatientsRouteImport.update({
  id: '/receptionist/patients',
  path: '/receptionist/patients',
  getParentRoute: () => AppRoute,
} as any)
const AppSuperAdminIndexRoute = AppSuperAdminIndexRouteImport.update({
  id: '/super-admin/',
  path: '/super-admin/',
  getParentRoute: () => AppRoute,
} as any)
const AppSuperAdminSplatRoute = AppSuperAdminSplatRouteImport.update({
  id: '/super-admin/$',
  path: '/super-admin/$',
  getParentRoute: () => AppRoute,
} as any)
const AppSuperAdminAppointmentsRoute =
  AppSuperAdminAppointmentsRouteImport.update({
    id: '/super-admin/appointments',
    path: '/super-admin/appointments',
    getParentRoute: () => AppRoute,
  } as any)
const AppSuperAdminAuditLogsRoute = AppSuperAdminAuditLogsRouteImport.update({
  id: '/super-admin/audit-logs',
  path: '/super-admin/audit-logs',
  getParentRoute: () => AppRoute,
} as any)
const AppSuperAdminBillsRoute = AppSuperAdminBillsRouteImport.update({
  id: '/super-admin/bills',
  path: '/super-admin/bills',
  getParentRoute: () => AppRoute,
} as any)
const AppSuperAdminCalendarRoute = AppSuperAdminCalendarRouteImport.update({
  id: '/super-admin/calendar',
  path: '/super-admin/calendar',
  getParentRoute: () => AppRoute,
} as any)
const AppSuperAdminDashboardRoute = AppSuperAdminDashboardRouteImport.update({
  id: '/super-admin/dashboard',
  path: '/super-admin/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppSuperAdminDoctorsRoute = AppSuperAdminDoctorsRouteImport.update({
  id: '/super-admin/doctors',
  path: '/super-admin/doctors',
  getParentRoute: () => AppRoute,
} as any)
const AppSuperAdminMedicalRecordsRoute =
  AppSuperAdminMedicalRecordsRouteImport.update({
    id: '/super-admin/medical-records',
    path: '/super-admin/medical-records',
    getParentRoute: () => AppRoute,
  } as any)
const AppSuperAdminPatientsRoute = AppSuperAdminPatientsRouteImport.update({
  id: '/super-admin/patients',
  path: '/super-admin/patients',
  getParentRoute: () => AppRoute,
} as any)
const AppSuperAdminReportsRoute = AppSuperAdminReportsRouteImport.update({
  id: '/super-admin/reports',
  path: '/super-admin/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppSuperAdminUsersRoute = AppSuperAdminUsersRouteImport.update({
  id: '/super-admin/users',
  path: '/super-admin/users',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/accountant/$': typeof AppAccountantSplatRoute
  '/accountant/appointments': typeof AppAccountantAppointmentsRoute
  '/accountant/bills': typeof AppAccountantBillsRoute
  '/accountant/calendar': typeof AppAccountantCalendarRoute
  '/accountant/dashboard': typeof AppAccountantDashboardRoute
  '/accountant/doctors': typeof AppAccountantDoctorsRoute
  '/accountant/patients': typeof AppAccountantPatientsRoute
  '/accountant/reports': typeof AppAccountantReportsRoute
  '/admin/$': typeof AppAdminSplatRoute
  '/admin/appointments': typeof AppAdminAppointmentsRoute
  '/admin/audit-logs': typeof AppAdminAuditLogsRoute
  '/admin/bills': typeof AppAdminBillsRoute
  '/admin/calendar': typeof AppAdminCalendarRoute
  '/admin/dashboard': typeof AppAdminDashboardRoute
  '/admin/doctors': typeof AppAdminDoctorsRoute
  '/admin/medical-records': typeof AppAdminMedicalRecordsRoute
  '/admin/patients': typeof AppAdminPatientsRoute
  '/admin/reports': typeof AppAdminReportsRoute
  '/admin/users': typeof AppAdminUsersRoute
  '/doctor/$': typeof AppDoctorSplatRoute
  '/doctor/appointments': typeof AppDoctorAppointmentsRoute
  '/doctor/calendar': typeof AppDoctorCalendarRoute
  '/doctor/dashboard': typeof AppDoctorDashboardRoute
  '/doctor/doctor-profile': typeof AppDoctorDoctorProfileRoute
  '/doctor/medical-records': typeof AppDoctorMedicalRecordsRoute
  '/patient/$': typeof AppPatientSplatRoute
  '/receptionist/$': typeof AppReceptionistSplatRoute
  '/receptionist/appointments': typeof AppReceptionistAppointmentsRoute
  '/receptionist/bills': typeof AppReceptionistBillsRoute
  '/receptionist/calendar': typeof AppReceptionistCalendarRoute
  '/receptionist/dashboard': typeof AppReceptionistDashboardRoute
  '/receptionist/doctors': typeof AppReceptionistDoctorsRoute
  '/receptionist/patients': typeof AppReceptionistPatientsRoute
  '/super-admin/$': typeof AppSuperAdminSplatRoute
  '/super-admin/appointments': typeof AppSuperAdminAppointmentsRoute
  '/super-admin/audit-logs': typeof AppSuperAdminAuditLogsRoute
  '/super-admin/bills': typeof AppSuperAdminBillsRoute
  '/super-admin/calendar': typeof AppSuperAdminCalendarRoute
  '/super-admin/dashboard': typeof AppSuperAdminDashboardRoute
  '/super-admin/doctors': typeof AppSuperAdminDoctorsRoute
  '/super-admin/medical-records': typeof AppSuperAdminMedicalRecordsRoute
  '/super-admin/patients': typeof AppSuperAdminPatientsRoute
  '/super-admin/reports': typeof AppSuperAdminReportsRoute
  '/super-admin/users': typeof AppSuperAdminUsersRoute
  '/accountant/': typeof AppAccountantIndexRoute
  '/admin/': typeof AppAdminIndexRoute
  '/doctor/': typeof AppDoctorIndexRoute
  '/patient/': typeof AppPatientIndexRoute
  '/receptionist/': typeof AppReceptionistIndexRoute
  '/super-admin/': typeof AppSuperAdminIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/': typeof AppIndexRoute
  '/accountant/$': typeof AppAccountantSplatRoute
  '/accountant/appointments': typeof AppAccountantAppointmentsRoute
  '/accountant/bills': typeof AppAccountantBillsRoute
  '/accountant/calendar': typeof AppAccountantCalendarRoute
  '/accountant/dashboard': typeof AppAccountantDashboardRoute
  '/accountant/doctors': typeof AppAccountantDoctorsRoute
  '/accountant/patients': typeof AppAccountantPatientsRoute
  '/accountant/reports': typeof AppAccountantReportsRoute
  '/admin/$': typeof AppAdminSplatRoute
  '/admin/appointments': typeof AppAdminAppointmentsRoute
  '/admin/audit-logs': typeof AppAdminAuditLogsRoute
  '/admin/bills': typeof AppAdminBillsRoute
  '/admin/calendar': typeof AppAdminCalendarRoute
  '/admin/dashboard': typeof AppAdminDashboardRoute
  '/admin/doctors': typeof AppAdminDoctorsRoute
  '/admin/medical-records': typeof AppAdminMedicalRecordsRoute
  '/admin/patients': typeof AppAdminPatientsRoute
  '/admin/reports': typeof AppAdminReportsRoute
  '/admin/users': typeof AppAdminUsersRoute
  '/doctor/$': typeof AppDoctorSplatRoute
  '/doctor/appointments': typeof AppDoctorAppointmentsRoute
  '/doctor/calendar': typeof AppDoctorCalendarRoute
  '/doctor/dashboard': typeof AppDoctorDashboardRoute
  '/doctor/doctor-profile': typeof AppDoctorDoctorProfileRoute
  '/doctor/medical-records': typeof AppDoctorMedicalRecordsRoute
  '/patient/$': typeof AppPatientSplatRoute
  '/receptionist/$': typeof AppReceptionistSplatRoute
  '/receptionist/appointments': typeof AppReceptionistAppointmentsRoute
  '/receptionist/bills': typeof AppReceptionistBillsRoute
  '/receptionist/calendar': typeof AppReceptionistCalendarRoute
  '/receptionist/dashboard': typeof AppReceptionistDashboardRoute
  '/receptionist/doctors': typeof AppReceptionistDoctorsRoute
  '/receptionist/patients': typeof AppReceptionistPatientsRoute
  '/super-admin/$': typeof AppSuperAdminSplatRoute
  '/super-admin/appointments': typeof AppSuperAdminAppointmentsRoute
  '/super-admin/audit-logs': typeof AppSuperAdminAuditLogsRoute
  '/super-admin/bills': typeof AppSuperAdminBillsRoute
  '/super-admin/calendar': typeof AppSuperAdminCalendarRoute
  '/super-admin/dashboard': typeof AppSuperAdminDashboardRoute
  '/super-admin/doctors': typeof AppSuperAdminDoctorsRoute
  '/super-admin/medical-records': typeof AppSuperAdminMedicalRecordsRoute
  '/super-admin/patients': typeof AppSuperAdminPatientsRoute
  '/super-admin/reports': typeof AppSuperAdminReportsRoute
  '/super-admin/users': typeof AppSuperAdminUsersRoute
  '/accountant': typeof AppAccountantIndexRoute
  '/admin': typeof AppAdminIndexRoute
  '/doctor': typeof AppDoctorIndexRoute
  '/patient': typeof AppPatientIndexRoute
  '/receptionist': typeof AppReceptionistIndexRoute
  '/super-admin': typeof AppSuperAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/': typeof AppIndexRoute
  '/_app/accountant/$': typeof AppAccountantSplatRoute
  '/_app/accountant/appointments': typeof AppAccountantAppointmentsRoute
  '/_app/accountant/bills': typeof AppAccountantBillsRoute
  '/_app/accountant/calendar': typeof AppAccountantCalendarRoute
  '/_app/accountant/dashboard': typeof AppAccountantDashboardRoute
  '/_app/accountant/doctors': typeof AppAccountantDoctorsRoute
  '/_app/accountant/patients': typeof AppAccountantPatientsRoute
  '/_app/accountant/reports': typeof AppAccountantReportsRoute
  '/_app/admin/$': typeof AppAdminSplatRoute
  '/_app/admin/appointments': typeof AppAdminAppointmentsRoute
  '/_app/admin/audit-logs': typeof AppAdminAuditLogsRoute
  '/_app/admin/bills': typeof AppAdminBillsRoute
  '/_app/admin/calendar': typeof AppAdminCalendarRoute
  '/_app/admin/dashboard': typeof AppAdminDashboardRoute
  '/_app/admin/doctors': typeof AppAdminDoctorsRoute
  '/_app/admin/medical-records': typeof AppAdminMedicalRecordsRoute
  '/_app/admin/patients': typeof AppAdminPatientsRoute
  '/_app/admin/reports': typeof AppAdminReportsRoute
  '/_app/admin/users': typeof AppAdminUsersRoute
  '/_app/doctor/$': typeof AppDoctorSplatRoute
  '/_app/doctor/appointments': typeof AppDoctorAppointmentsRoute
  '/_app/doctor/calendar': typeof AppDoctorCalendarRoute
  '/_app/doctor/dashboard': typeof AppDoctorDashboardRoute
  '/_app/doctor/doctor-profile': typeof AppDoctorDoctorProfileRoute
  '/_app/doctor/medical-records': typeof AppDoctorMedicalRecordsRoute
  '/_app/patient/$': typeof AppPatientSplatRoute
  '/_app/receptionist/$': typeof AppReceptionistSplatRoute
  '/_app/receptionist/appointments': typeof AppReceptionistAppointmentsRoute
  '/_app/receptionist/bills': typeof AppReceptionistBillsRoute
  '/_app/receptionist/calendar': typeof AppReceptionistCalendarRoute
  '/_app/receptionist/dashboard': typeof AppReceptionistDashboardRoute
  '/_app/receptionist/doctors': typeof AppReceptionistDoctorsRoute
  '/_app/receptionist/patients': typeof AppReceptionistPatientsRoute
  '/_app/super-admin/$': typeof AppSuperAdminSplatRoute
  '/_app/super-admin/appointments': typeof AppSuperAdminAppointmentsRoute
  '/_app/super-admin/audit-logs': typeof AppSuperAdminAuditLogsRoute
  '/_app/super-admin/bills': typeof AppSuperAdminBillsRoute
  '/_app/super-admin/calendar': typeof AppSuperAdminCalendarRoute
  '/_app/super-admin/dashboard': typeof AppSuperAdminDashboardRoute
  '/_app/super-admin/doctors': typeof AppSuperAdminDoctorsRoute
  '/_app/super-admin/medical-records': typeof AppSuperAdminMedicalRecordsRoute
  '/_app/super-admin/patients': typeof AppSuperAdminPatientsRoute
  '/_app/super-admin/reports': typeof AppSuperAdminReportsRoute
  '/_app/super-admin/users': typeof AppSuperAdminUsersRoute
  '/_app/accountant/': typeof AppAccountantIndexRoute
  '/_app/admin/': typeof AppAdminIndexRoute
  '/_app/doctor/': typeof AppDoctorIndexRoute
  '/_app/patient/': typeof AppPatientIndexRoute
  '/_app/receptionist/': typeof AppReceptionistIndexRoute
  '/_app/super-admin/': typeof AppSuperAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/accountant/$'
    | '/accountant/appointments'
    | '/accountant/bills'
    | '/accountant/calendar'
    | '/accountant/dashboard'
    | '/accountant/doctors'
    | '/accountant/patients'
    | '/accountant/reports'
    | '/admin/$'
    | '/admin/appointments'
    | '/admin/audit-logs'
    | '/admin/bills'
    | '/admin/calendar'
    | '/admin/dashboard'
    | '/admin/doctors'
    | '/admin/medical-records'
    | '/admin/patients'
    | '/admin/reports'
    | '/admin/users'
    | '/doctor/$'
    | '/doctor/appointments'
    | '/doctor/calendar'
    | '/doctor/dashboard'
    | '/doctor/doctor-profile'
    | '/doctor/medical-records'
    | '/patient/$'
    | '/receptionist/$'
    | '/receptionist/appointments'
    | '/receptionist/bills'
    | '/receptionist/calendar'
    | '/receptionist/dashboard'
    | '/receptionist/doctors'
    | '/receptionist/patients'
    | '/super-admin/$'
    | '/super-admin/appointments'
    | '/super-admin/audit-logs'
    | '/super-admin/bills'
    | '/super-admin/calendar'
    | '/super-admin/dashboard'
    | '/super-admin/doctors'
    | '/super-admin/medical-records'
    | '/super-admin/patients'
    | '/super-admin/reports'
    | '/super-admin/users'
    | '/accountant/'
    | '/admin/'
    | '/doctor/'
    | '/patient/'
    | '/receptionist/'
    | '/super-admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/'
    | '/accountant/$'
    | '/accountant/appointments'
    | '/accountant/bills'
    | '/accountant/calendar'
    | '/accountant/dashboard'
    | '/accountant/doctors'
    | '/accountant/patients'
    | '/accountant/reports'
    | '/admin/$'
    | '/admin/appointments'
    | '/admin/audit-logs'
    | '/admin/bills'
    | '/admin/calendar'
    | '/admin/dashboard'
    | '/admin/doctors'
    | '/admin/medical-records'
    | '/admin/patients'
    | '/admin/reports'
    | '/admin/users'
    | '/doctor/$'
    | '/doctor/appointments'
    | '/doctor/calendar'
    | '/doctor/dashboard'
    | '/doctor/doctor-profile'
    | '/doctor/medical-records'
    | '/patient/$'
    | '/receptionist/$'
    | '/receptionist/appointments'
    | '/receptionist/bills'
    | '/receptionist/calendar'
    | '/receptionist/dashboard'
    | '/receptionist/doctors'
    | '/receptionist/patients'
    | '/super-admin/$'
    | '/super-admin/appointments'
    | '/super-admin/audit-logs'
    | '/super-admin/bills'
    | '/super-admin/calendar'
    | '/super-admin/dashboard'
    | '/super-admin/doctors'
    | '/super-admin/medical-records'
    | '/super-admin/patients'
    | '/super-admin/reports'
    | '/super-admin/users'
    | '/accountant'
    | '/admin'
    | '/doctor'
    | '/patient'
    | '/receptionist'
    | '/super-admin'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/'
    | '/_app/accountant/$'
    | '/_app/accountant/appointments'
    | '/_app/accountant/bills'
    | '/_app/accountant/calendar'
    | '/_app/accountant/dashboard'
    | '/_app/accountant/doctors'
    | '/_app/accountant/patients'
    | '/_app/accountant/reports'
    | '/_app/admin/$'
    | '/_app/admin/appointments'
    | '/_app/admin/audit-logs'
    | '/_app/admin/bills'
    | '/_app/admin/calendar'
    | '/_app/admin/dashboard'
    | '/_app/admin/doctors'
    | '/_app/admin/medical-records'
    | '/_app/admin/patients'
    | '/_app/admin/reports'
    | '/_app/admin/users'
    | '/_app/doctor/$'
    | '/_app/doctor/appointments'
    | '/_app/doctor/calendar'
    | '/_app/doctor/dashboard'
    | '/_app/doctor/doctor-profile'
    | '/_app/doctor/medical-records'
    | '/_app/patient/$'
    | '/_app/receptionist/$'
    | '/_app/receptionist/appointments'
    | '/_app/receptionist/bills'
    | '/_app/receptionist/calendar'
    | '/_app/receptionist/dashboard'
    | '/_app/receptionist/doctors'
    | '/_app/receptionist/patients'
    | '/_app/super-admin/$'
    | '/_app/super-admin/appointments'
    | '/_app/super-admin/audit-logs'
    | '/_app/super-admin/bills'
    | '/_app/super-admin/calendar'
    | '/_app/super-admin/dashboard'
    | '/_app/super-admin/doctors'
    | '/_app/super-admin/medical-records'
    | '/_app/super-admin/patients'
    | '/_app/super-admin/reports'
    | '/_app/super-admin/users'
    | '/_app/accountant/'
    | '/_app/admin/'
    | '/_app/doctor/'
    | '/_app/patient/'
    | '/_app/receptionist/'
    | '/_app/super-admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/accountant/': {
      id: '/_app/accountant/'
      path: '/accountant'
      fullPath: '/accountant/'
      preLoaderRoute: typeof AppAccountantIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/accountant/$': {
      id: '/_app/accountant/$'
      path: '/accountant/$'
      fullPath: '/accountant/$'
      preLoaderRoute: typeof AppAccountantSplatRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/accountant/appointments': {
      id: '/_app/accountant/appointments'
      path: '/accountant/appointments'
      fullPath: '/accountant/appointments'
      preLoaderRoute: typeof AppAccountantAppointmentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/accountant/bills': {
      id: '/_app/accountant/bills'
      path: '/accountant/bills'
      fullPath: '/accountant/bills'
      preLoaderRoute: typeof AppAccountantBillsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/accountant/calendar': {
      id: '/_app/accountant/calendar'
      path: '/accountant/calendar'
      fullPath: '/accountant/calendar'
      preLoaderRoute: typeof AppAccountantCalendarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/accountant/dashboard': {
      id: '/_app/accountant/dashboard'
      path: '/accountant/dashboard'
      fullPath: '/accountant/dashboard'
      preLoaderRoute: typeof AppAccountantDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/accountant/doctors': {
      id: '/_app/accountant/doctors'
      path: '/accountant/doctors'
      fullPath: '/accountant/doctors'
      preLoaderRoute: typeof AppAccountantDoctorsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/accountant/patients': {
      id: '/_app/accountant/patients'
      path: '/accountant/patients'
      fullPath: '/accountant/patients'
      preLoaderRoute: typeof AppAccountantPatientsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/accountant/reports': {
      id: '/_app/accountant/reports'
      path: '/accountant/reports'
      fullPath: '/accountant/reports'
      preLoaderRoute: typeof AppAccountantReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/': {
      id: '/_app/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AppAdminIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/$': {
      id: '/_app/admin/$'
      path: '/admin/$'
      fullPath: '/admin/$'
      preLoaderRoute: typeof AppAdminSplatRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/appointments': {
      id: '/_app/admin/appointments'
      path: '/admin/appointments'
      fullPath: '/admin/appointments'
      preLoaderRoute: typeof AppAdminAppointmentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/audit-logs': {
      id: '/_app/admin/audit-logs'
      path: '/admin/audit-logs'
      fullPath: '/admin/audit-logs'
      preLoaderRoute: typeof AppAdminAuditLogsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/bills': {
      id: '/_app/admin/bills'
      path: '/admin/bills'
      fullPath: '/admin/bills'
      preLoaderRoute: typeof AppAdminBillsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/calendar': {
      id: '/_app/admin/calendar'
      path: '/admin/calendar'
      fullPath: '/admin/calendar'
      preLoaderRoute: typeof AppAdminCalendarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/dashboard': {
      id: '/_app/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AppAdminDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/doctors': {
      id: '/_app/admin/doctors'
      path: '/admin/doctors'
      fullPath: '/admin/doctors'
      preLoaderRoute: typeof AppAdminDoctorsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/medical-records': {
      id: '/_app/admin/medical-records'
      path: '/admin/medical-records'
      fullPath: '/admin/medical-records'
      preLoaderRoute: typeof AppAdminMedicalRecordsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/patients': {
      id: '/_app/admin/patients'
      path: '/admin/patients'
      fullPath: '/admin/patients'
      preLoaderRoute: typeof AppAdminPatientsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/reports': {
      id: '/_app/admin/reports'
      path: '/admin/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AppAdminReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/users': {
      id: '/_app/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AppAdminUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/doctor/': {
      id: '/_app/doctor/'
      path: '/doctor'
      fullPath: '/doctor/'
      preLoaderRoute: typeof AppDoctorIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/doctor/$': {
      id: '/_app/doctor/$'
      path: '/doctor/$'
      fullPath: '/doctor/$'
      preLoaderRoute: typeof AppDoctorSplatRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/doctor/appointments': {
      id: '/_app/doctor/appointments'
      path: '/doctor/appointments'
      fullPath: '/doctor/appointments'
      preLoaderRoute: typeof AppDoctorAppointmentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/doctor/calendar': {
      id: '/_app/doctor/calendar'
      path: '/doctor/calendar'
      fullPath: '/doctor/calendar'
      preLoaderRoute: typeof AppDoctorCalendarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/doctor/dashboard': {
      id: '/_app/doctor/dashboard'
      path: '/doctor/dashboard'
      fullPath: '/doctor/dashboard'
      preLoaderRoute: typeof AppDoctorDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/doctor/doctor-profile': {
      id: '/_app/doctor/doctor-profile'
      path: '/doctor/doctor-profile'
      fullPath: '/doctor/doctor-profile'
      preLoaderRoute: typeof AppDoctorDoctorProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/doctor/medical-records': {
      id: '/_app/doctor/medical-records'
      path: '/doctor/medical-records'
      fullPath: '/doctor/medical-records'
      preLoaderRoute: typeof AppDoctorMedicalRecordsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/patient/': {
      id: '/_app/patient/'
      path: '/patient'
      fullPath: '/patient/'
      preLoaderRoute: typeof AppPatientIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/patient/$': {
      id: '/_app/patient/$'
      path: '/patient/$'
      fullPath: '/patient/$'
      preLoaderRoute: typeof AppPatientSplatRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/receptionist/': {
      id: '/_app/receptionist/'
      path: '/receptionist'
      fullPath: '/receptionist/'
      preLoaderRoute: typeof AppReceptionistIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/receptionist/$': {
      id: '/_app/receptionist/$'
      path: '/receptionist/$'
      fullPath: '/receptionist/$'
      preLoaderRoute: typeof AppReceptionistSplatRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/receptionist/appointments': {
      id: '/_app/receptionist/appointments'
      path: '/receptionist/appointments'
      fullPath: '/receptionist/appointments'
      preLoaderRoute: typeof AppReceptionistAppointmentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/receptionist/bills': {
      id: '/_app/receptionist/bills'
      path: '/receptionist/bills'
      fullPath: '/receptionist/bills'
      preLoaderRoute: typeof AppReceptionistBillsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/receptionist/calendar': {
      id: '/_app/receptionist/calendar'
      path: '/receptionist/calendar'
      fullPath: '/receptionist/calendar'
      preLoaderRoute: typeof AppReceptionistCalendarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/receptionist/dashboard': {
      id: '/_app/receptionist/dashboard'
      path: '/receptionist/dashboard'
      fullPath: '/receptionist/dashboard'
      preLoaderRoute: typeof AppReceptionistDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/receptionist/doctors': {
      id: '/_app/receptionist/doctors'
      path: '/receptionist/doctors'
      fullPath: '/receptionist/doctors'
      preLoaderRoute: typeof AppReceptionistDoctorsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/receptionist/patients': {
      id: '/_app/receptionist/patients'
      path: '/receptionist/patients'
      fullPath: '/receptionist/patients'
      preLoaderRoute: typeof AppReceptionistPatientsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/super-admin/': {
      id: '/_app/super-admin/'
      path: '/super-admin'
      fullPath: '/super-admin/'
      preLoaderRoute: typeof AppSuperAdminIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/super-admin/$': {
      id: '/_app/super-admin/$'
      path: '/super-admin/$'
      fullPath: '/super-admin/$'
      preLoaderRoute: typeof AppSuperAdminSplatRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/super-admin/appointments': {
      id: '/_app/super-admin/appointments'
      path: '/super-admin/appointments'
      fullPath: '/super-admin/appointments'
      preLoaderRoute: typeof AppSuperAdminAppointmentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/super-admin/audit-logs': {
      id: '/_app/super-admin/audit-logs'
      path: '/super-admin/audit-logs'
      fullPath: '/super-admin/audit-logs'
      preLoaderRoute: typeof AppSuperAdminAuditLogsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/super-admin/bills': {
      id: '/_app/super-admin/bills'
      path: '/super-admin/bills'
      fullPath: '/super-admin/bills'
      preLoaderRoute: typeof AppSuperAdminBillsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/super-admin/calendar': {
      id: '/_app/super-admin/calendar'
      path: '/super-admin/calendar'
      fullPath: '/super-admin/calendar'
      preLoaderRoute: typeof AppSuperAdminCalendarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/super-admin/dashboard': {
      id: '/_app/super-admin/dashboard'
      path: '/super-admin/dashboard'
      fullPath: '/super-admin/dashboard'
      preLoaderRoute: typeof AppSuperAdminDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/super-admin/doctors': {
      id: '/_app/super-admin/doctors'
      path: '/super-admin/doctors'
      fullPath: '/super-admin/doctors'
      preLoaderRoute: typeof AppSuperAdminDoctorsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/super-admin/medical-records': {
      id: '/_app/super-admin/medical-records'
      path: '/super-admin/medical-records'
      fullPath: '/super-admin/medical-records'
      preLoaderRoute: typeof AppSuperAdminMedicalRecordsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/super-admin/patients': {
      id: '/_app/super-admin/patients'
      path: '/super-admin/patients'
      fullPath: '/super-admin/patients'
      preLoaderRoute: typeof AppSuperAdminPatientsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/super-admin/reports': {
      id: '/_app/super-admin/reports'
      path: '/super-admin/reports'
      fullPath: '/super-admin/reports'
      preLoaderRoute: typeof AppSuperAdminReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/super-admin/users': {
      id: '/_app/super-admin/users'
      path: '/super-admin/users'
      fullPath: '/super-admin/users'
      preLoaderRoute: typeof AppSuperAdminUsersRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppAccountantSplatRoute: typeof AppAccountantSplatRoute
  AppAccountantAppointmentsRoute: typeof AppAccountantAppointmentsRoute
  AppAccountantBillsRoute: typeof AppAccountantBillsRoute
  AppAccountantCalendarRoute: typeof AppAccountantCalendarRoute
  AppAccountantDashboardRoute: typeof AppAccountantDashboardRoute
  AppAccountantDoctorsRoute: typeof AppAccountantDoctorsRoute
  AppAccountantPatientsRoute: typeof AppAccountantPatientsRoute
  AppAccountantReportsRoute: typeof AppAccountantReportsRoute
  AppAdminSplatRoute: typeof AppAdminSplatRoute
  AppAdminAppointmentsRoute: typeof AppAdminAppointmentsRoute
  AppAdminAuditLogsRoute: typeof AppAdminAuditLogsRoute
  AppAdminBillsRoute: typeof AppAdminBillsRoute
  AppAdminCalendarRoute: typeof AppAdminCalendarRoute
  AppAdminDashboardRoute: typeof AppAdminDashboardRoute
  AppAdminDoctorsRoute: typeof AppAdminDoctorsRoute
  AppAdminMedicalRecordsRoute: typeof AppAdminMedicalRecordsRoute
  AppAdminPatientsRoute: typeof AppAdminPatientsRoute
  AppAdminReportsRoute: typeof AppAdminReportsRoute
  AppAdminUsersRoute: typeof AppAdminUsersRoute
  AppDoctorSplatRoute: typeof AppDoctorSplatRoute
  AppDoctorAppointmentsRoute: typeof AppDoctorAppointmentsRoute
  AppDoctorCalendarRoute: typeof AppDoctorCalendarRoute
  AppDoctorDashboardRoute: typeof AppDoctorDashboardRoute
  AppDoctorDoctorProfileRoute: typeof AppDoctorDoctorProfileRoute
  AppDoctorMedicalRecordsRoute: typeof AppDoctorMedicalRecordsRoute
  AppPatientSplatRoute: typeof AppPatientSplatRoute
  AppReceptionistSplatRoute: typeof AppReceptionistSplatRoute
  AppReceptionistAppointmentsRoute: typeof AppReceptionistAppointmentsRoute
  AppReceptionistBillsRoute: typeof AppReceptionistBillsRoute
  AppReceptionistCalendarRoute: typeof AppReceptionistCalendarRoute
  AppReceptionistDashboardRoute: typeof AppReceptionistDashboardRoute
  AppReceptionistDoctorsRoute: typeof AppReceptionistDoctorsRoute
  AppReceptionistPatientsRoute: typeof AppReceptionistPatientsRoute
  AppSuperAdminSplatRoute: typeof AppSuperAdminSplatRoute
  AppSuperAdminAppointmentsRoute: typeof AppSuperAdminAppointmentsRoute
  AppSuperAdminAuditLogsRoute: typeof AppSuperAdminAuditLogsRoute
  AppSuperAdminBillsRoute: typeof AppSuperAdminBillsRoute
  AppSuperAdminCalendarRoute: typeof AppSuperAdminCalendarRoute
  AppSuperAdminDashboardRoute: typeof AppSuperAdminDashboardRoute
  AppSuperAdminDoctorsRoute: typeof AppSuperAdminDoctorsRoute
  AppSuperAdminMedicalRecordsRoute: typeof AppSuperAdminMedicalRecordsRoute
  AppSuperAdminPatientsRoute: typeof AppSuperAdminPatientsRoute
  AppSuperAdminReportsRoute: typeof AppSuperAdminReportsRoute
  AppSuperAdminUsersRoute: typeof AppSuperAdminUsersRoute
  AppAccountantIndexRoute: typeof AppAccountantIndexRoute
  AppAdminIndexRoute: typeof AppAdminIndexRoute
  AppDoctorIndexRoute: typeof AppDoctorIndexRoute
  AppPatientIndexRoute: typeof AppPatientIndexRoute
  AppReceptionistIndexRoute: typeof AppReceptionistIndexRoute
  AppSuperAdminIndexRoute: typeof AppSuperAdminIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppAccountantSplatRoute: AppAccountantSplatRoute,
  AppAccountantAppointmentsRoute: AppAccountantAppointmentsRoute,
  AppAccountantBillsRoute: AppAccountantBillsRoute,
  AppAccountantCalendarRoute: AppAccountantCalendarRoute,
  AppAccountantDashboardRoute: AppAccountantDashboardRoute,
  AppAccountantDoctorsRoute: AppAccountantDoctorsRoute,
  AppAccountantPatientsRoute: AppAccountantPatientsRoute,
  AppAccountantReportsRoute: AppAccountantReportsRoute,
  AppAdminSplatRoute: AppAdminSplatRoute,
  AppAdminAppointmentsRoute: AppAdminAppointmentsRoute,
  AppAdminAuditLogsRoute: AppAdminAuditLogsRoute,
  AppAdminBillsRoute: AppAdminBillsRoute,
  AppAdminCalendarRoute: AppAdminCalendarRoute,
  AppAdminDashboardRoute: AppAdminDashboardRoute,
  AppAdminDoctorsRoute: AppAdminDoctorsRoute,
  AppAdminMedicalRecordsRoute: AppAdminMedicalRecordsRoute,
  AppAdminPatientsRoute: AppAdminPatientsRoute,
  AppAdminReportsRoute: AppAdminReportsRoute,
  AppAdminUsersRoute: AppAdminUsersRoute,
  AppDoctorSplatRoute: AppDoctorSplatRoute,
  AppDoctorAppointmentsRoute: AppDoctorAppointmentsRoute,
  AppDoctorCalendarRoute: AppDoctorCalendarRoute,
  AppDoctorDashboardRoute: AppDoctorDashboardRoute,
  AppDoctorDoctorProfileRoute: AppDoctorDoctorProfileRoute,
  AppDoctorMedicalRecordsRoute: AppDoctorMedicalRecordsRoute,
  AppPatientSplatRoute: AppPatientSplatRoute,
  AppReceptionistSplatRoute: AppReceptionistSplatRoute,
  AppReceptionistAppointmentsRoute: AppReceptionistAppointmentsRoute,
  AppReceptionistBillsRoute: AppReceptionistBillsRoute,
  AppReceptionistCalendarRoute: AppReceptionistCalendarRoute,
  AppReceptionistDashboardRoute: AppReceptionistDashboardRoute,
  AppReceptionistDoctorsRoute: AppReceptionistDoctorsRoute,
  AppReceptionistPatientsRoute: AppReceptionistPatientsRoute,
  AppSuperAdminSplatRoute: AppSuperAdminSplatRoute,
  AppSuperAdminAppointmentsRoute: AppSuperAdminAppointmentsRoute,
  AppSuperAdminAuditLogsRoute: AppSuperAdminAuditLogsRoute,
  AppSuperAdminBillsRoute: AppSuperAdminBillsRoute,
  AppSuperAdminCalendarRoute: AppSuperAdminCalendarRoute,
  AppSuperAdminDashboardRoute: AppSuperAdminDashboardRoute,
  AppSuperAdminDoctorsRoute: AppSuperAdminDoctorsRoute,
  AppSuperAdminMedicalRecordsRoute: AppSuperAdminMedicalRecordsRoute,
  AppSuperAdminPatientsRoute: AppSuperAdminPatientsRoute,
  AppSuperAdminReportsRoute: AppSuperAdminReportsRoute,
  AppSuperAdminUsersRoute: AppSuperAdminUsersRoute,
  AppAccountantIndexRoute: AppAccountantIndexRoute,
  AppAdminIndexRoute: AppAdminIndexRoute,
  AppDoctorIndexRoute: AppDoctorIndexRoute,
  AppPatientIndexRoute: AppPatientIndexRoute,
  AppReceptionistIndexRoute: AppReceptionistIndexRoute,
  AppSuperAdminIndexRoute: AppSuperAdminIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
