version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: backend

    ports:
      - "3000:3000"

    env_file:
      - .env

    volumes:
      - .:/app
      - /app/node_modules

    command: bun run --watch index.ts

    restart: unless-stopped

    depends_on:
      - postgres

  postgres:
    image: postgres:17

    container_name: postgres

    restart: unless-stopped

    environment:
      POSTGRES_DB: app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"

    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
